### PR TITLE
adding DividerDemo

### PR DESCRIPTION
**Pull request by odorifqi**
is there another props for the `<Divider/>` ? Let me know if there any, thanks.

### CODE REVIEW

**Comment by odorifqi** [comment]
#17

**Review by jpalacio0612 — CHANGES_REQUESTED** [review]
Great job!, Could you add the following props to the general table:

- orientation
- disabled
- thick

Maybe you want to see the code of that component in the library, this is the link:
[https://github.com/jpalacio0612/react-neon-ui/blob/main/src/components/Divider/Divider.js](https://github.com/jpalacio0612/react-neon-ui/blob/main/src/components/Divider/Divider.js)

**Comment by odorifqi** [comment]
okay, nice, be right back!

**Review by jpalacio0612 — APPROVED** [review]
Great Job!, Thanks! 🚀

**Pull request merged**
